// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $products_product_id_ from "./routes/products/[product_id].tsx";
import * as $products_list_products from "./routes/products/list-products.tsx";
import * as $products_load_example_json_name_ from "./routes/products/load-example/[json_name].tsx";
import * as $AddEditProduct from "./islands/AddEditProduct.tsx";
import * as $ExampleLoader from "./islands/ExampleLoader.tsx";
import * as $ListProducts from "./islands/ListProducts.tsx";
import * as $RecipeSelect from "./islands/RecipeSelect.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/products/[product_id].tsx": $products_product_id_,
    "./routes/products/list-products.tsx": $products_list_products,
    "./routes/products/load-example/[json_name].tsx":
      $products_load_example_json_name_,
  },
  islands: {
    "./islands/AddEditProduct.tsx": $AddEditProduct,
    "./islands/ExampleLoader.tsx": $ExampleLoader,
    "./islands/ListProducts.tsx": $ListProducts,
    "./islands/RecipeSelect.tsx": $RecipeSelect,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
